### ISSUE TITLE
在手机上或者浏览器宽度调小以后，dark/light的按钮没了？

### ISSUE THREAD

**Issue by guanyc** [wayjam/hugo-theme-fluency#1]
<img width="482" alt="Screen Shot 2021-06-19 at 2 01 27 PM" src="https://user-images.githubusercontent.com/555099/122632657-e7914b80-d106-11eb-8243-8d4a1c95172f.png">

**Comment by wayjam** [comment]
设计如此。移动设备按系统主题色自动切换，没有手动切换。
